name: Cron Job Every 2 Min

on:
  schedule:
    # Every 5 minutes 
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  cron-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print time
        run: echo "✅ Cron job triggered successfully at $(date)"
