name: Cron Job Every 2 Min

on:
  

  workflow_dispatch:

jobs:
  cron-task:
    runs-on: ubuntu-latest
    steps:
      - name: Show current working directory
        run: pwd

      - name: List files in the directory
        run: lw ld 
